//! Mines blocks on a local regtest chain, end to end.
//!
//! ```text
//! cargo run --release -p regtest-miner -- [block count]
//! ```
//!
//! Regtest difficulty is trivial — the target covers roughly half the hash
//! space — so a block is found in a handful of attempts. That is the point: it
//! makes the mine-and-submit path testable in milliseconds instead of
//! geological time, so the parts that are actually hard to get right (the
//! five-stage proof of work, the 164-byte header, the coinbase, the witness
//! commitment, the merkle root) can be debugged against a real node.
//!
//! Every consensus rule that applies on mainnet applies here too. A block this
//! accepts is wrong in no way that regtest is lenient about — including the
//! two rules the fork added, which is why the activation height is set to 10
//! in `config/btcb2.regtest.conf` rather than left at its default. A chain
//! mined from genesis therefore crosses the fork, and the code that handles
//! the crossing is exercised rather than assumed.

mod chain;
mod round;

use btcb2_primitives::hex;
use mining::NonceSpace;
use node_rpc::{Network, RpcClient};
use std::path::PathBuf;

/// The wallet used to generate a throwaway payout address on regtest.
const WALLET_NAME: &str = "btcb2-miner-regtest";

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");

        // Print the whole cause chain: the root is usually the useful part,
        // and Display on the outermost error only shows the top.
        let mut source = error.source();
        while let Some(cause) = source {
            eprintln!("  caused by: {cause}");
            source = cause.source();
        }

        std::process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let blocks_to_mine: u32 = std::env::args()
        .nth(1)
        .map_or(Ok(1), |argument| argument.parse())?;

    let datadir = datadir();
    let client = RpcClient::from_datadir(&datadir, Network::Regtest)?;

    // --- Refuse to mine on a node that is not where we think it is ----------
    //
    // Worth more here than it would be on Bitcoin. This fork kept Bitcoin's
    // network magic and RPC ports, so a datadir mix-up produces a node that
    // starts, answers, and quietly disagrees about which chain is real.
    let info = client.get_blockchain_info()?;
    if info.chain != Network::Regtest.as_str() {
        return Err(format!(
            "expected a regtest node, but {} is running {}",
            datadir.display(),
            info.chain
        )
        .into());
    }

    println!("node   : regtest at height {}", info.blocks);

    // --- Payout address ------------------------------------------------------
    //
    // Generated by the node's wallet, because on regtest the coins are
    // meaningless. On the public networks this comes from the user instead.
    client.ensure_wallet(WALLET_NAME)?;
    let address = client.get_new_address(WALLET_NAME)?;

    let address_info = client.validate_address(&address)?;
    if !address_info.is_valid {
        return Err(format!("the node produced an address it considers invalid: {address}").into());
    }
    let payout_script = hex::decode(
        address_info
            .script_pubkey
            .as_deref()
            .ok_or("validateaddress returned no scriptPubKey")?,
    )?;

    println!("payout : {address}");
    println!("script : {}\n", hex::encode(&payout_script));

    let headline = chain::headline(Network::Regtest);

    // --- Mine ----------------------------------------------------------------
    for round_number in 1..=blocks_to_mine {
        let template = client.get_block_template()?;

        // The extranonce must differ per attempt so that a repeated template
        // cannot produce a byte-identical block.
        let extranonce = u64::from(round_number);

        match round::mine(
            &client,
            &template,
            &payout_script,
            extranonce,
            headline.as_deref(),
            // Start each round somewhere new. Putting the round number in
            // `time_offset` is not arbitrary: that word is a free nonce only
            // while the `UseTimeOffset` flag is clear, which is a claim about
            // this fork's consensus rules rather than something the code can
            // check. Mining with it non-zero from the second block onward puts
            // the claim in front of a real node every single run.
            NonceSpace { time_offset: round_number, ..Default::default() },
        )? {
            round::Outcome::Accepted { hash, height, at, hashes } => {
                let kind = if template.header_v2() { "v2" } else { "v1" };
                println!("block {height} accepted  ({kind} header)");
                println!("  hash   : {hash}");
                println!(
                    "  nonces : {} {} {} {}  (found after {hashes} hashes)",
                    at.nonce, at.nonce2, at.nonce3, at.time_offset
                );
            }
            round::Outcome::Rejected { reason } => {
                return Err(format!("the node rejected the block: {reason}").into());
            }
            round::Outcome::Exhausted { best, best_zero_bits, needed_zero_bits } => {
                return Err(format!(
                    "ran out of attempts without a solution \
                     (best was {best}, {best_zero_bits} of the {needed_zero_bits} \
                      leading zero bits needed)"
                )
                .into());
            }
        }
    }

    let info = client.get_blockchain_info()?;
    println!("\nchain is now at height {}", info.blocks);
    println!("tip: {}", info.best_block_hash);

    Ok(())
}

/// Where the node keeps its data. Matches `scripts/node.sh`.
fn datadir() -> PathBuf {
    std::env::var("BTCB2_DATADIR").map_or_else(
        |_| PathBuf::from(std::env::var("HOME").expect("HOME is set")).join(".btcb2"),
        PathBuf::from,
    )
}
